baseurl = "/"
languageCode = "en"
theme = "terminal"
paginate = 5
enableEmoji = true

[params]
  contentTypeName = "post"
  themeColor = "green"
  showMenuItems = 5
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true
  showLastUpdated = false
  googleAnalytics = "123456"
  # favicon = "favicon.ico"

[permalinks]
  post = "/:slug"

[languages]
  [languages.en]
    languageName = "English"
    title = "leocarmo.dev"
    subtitle = "Um blog de dev"
    owner = "leocarmo.dev"
    keywords = ""
    copyright = "leocarmo.dev"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "leocarmo.dev"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "github"
        name = "github"
        url = "https://github.com/leocarmo"
      [[languages.en.menu.main]]
        identifier = "linkedin"
        name = "linkedin"
        url = "https://www.linkedin.com/in/leonardocarmo/"
      [[languages.en.menu.main]]
        identifier = "rss"
        name = "rss"
        url = "/index.xml"